name: Gradle Github Actions

on: [push]

jobs:
  build:
    strategy:
      matrix:
        java: ['8']
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v1

      - name: Set up JDK ${{ matrix.java }}
        uses: actions/setup-java@v1
        with:
          java-version: ${{ matrix.java }}
          architecture: x64

      - name: Make gradlew executable
        run: chmod +x ./gradlew

      - name: Build with Gradle
        run: ./gradlew --no-daemon

      - uses: actions/upload-artifact@master
        with:
          name: HDSkins-1.8
          path: build/libs/HDSkins.jar